### ISSUE TITLE
Clicking on some triangles of a mesh does not select the mesh

### ISSUE THREAD

**Issue by VBoschMatas** [AkitaInteractive/Hachiko-Engine#7]
Raycast or triangles are not detected or checked correctly. To try it out try to select Baker House's chimney clicking on the top part of the chimney from a frontal or lateral view

**Comment by armandojaga** [comment]
@VBoschMatas is this still an issue?

**Comment by VBoschMatas** [comment]
It is not what I thought it was. But in the last level there are te column GameObject that can not be selected for some reason, and I dont know if its an engine problem or model problem. If you want we can close this issue though
