### ISSUE TITLE
Crash when trying to load .scene with drag and drop

### ISSUE THREAD

**Issue by EdwardRegasDuncan** [AkitaInteractive/Hachiko-Engine#80]
When loading a scene file by dragging it over from file explorer, shows the following error then crash:

![image](https://user-images.githubusercontent.com/19652627/165946455-d5d60b78-cf1f-436d-893f-cc77f49e198b.png)

**Comment by Bernatmago** [comment]
Hi Edward, this issue was because scene was not really managed as a resource so it did not find an importer for itself. This issue has been resolved with the most recent RM updates. Thanks a lot for the feedack <3
