### ISSUE TITLE
Crash when swaping from Hierarchy to Scene if grouped

### ISSUE THREAD

**Issue by OGKoko** [AkitaInteractive/Hachiko-Engine#84]
![image_2022-05-01_201756705](https://user-images.githubusercontent.com/21370517/166159062-5e0694b3-bd8f-42c8-a317-d53ea5b0fe02.png)

If you use the Whatever and Scene on the **same window** and you swap between them it crashes.
in this case it shows the Hierarchy, but happens if you do it with the Console or Resources tab aswell.

**Comment by Bernatmago** [comment]
Im closing this since it seems to be working fine in the current version, thanks for your feedback
