### ISSUE TITLE
Stencil buffer for picked object border to have priority on top of not picked objects

### ISSUE THREAD

**Issue by VBoschMatas** [AkitaInteractive/Hachiko-Engine#9]
If an object gets selected let the border be always visible, even if there are objects in front of it.

*Note: this is just an optional enhancement request, 0 priority and totally optional.*

**Comment by armandojaga** [comment]
@VBoschMatas is this still an issue?

**Comment by VBoschMatas** [comment]
> @VBoschMatas is this still an issue?

It hasn't been adressed yet, stencil is just an optional comodity, so I've been focusing on improving other part of the engine

**Comment by monikamnc** [comment]
We don't have stencil buffer so I close this :3
